my_string = input('Произвольная строка: ')
leng = len(my_string)
print(leng)
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(my_string[0])
print(my_string[-1])
